[package]
name = "wiki-tui"
version = "0.1.0"
authors = ["builditluc <37375448+Builditluc@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
dotenv = "0.15.0"
cursive = "0.15.0"
syn = "=1.0.57"
serde_json = "1.0.61"
simple-logging = "2.0.2"
log = "0.4.13"

[dependencies.diesel]
version = "1.4.4"
features = ["sqlite", "uuid", "chrono"]

[dependencies.uuid]
version = "0.8.1"
features = ["serde", "v4"]

[dependencies.reqwest]
version = "0.11"
features = ["json", "blocking"]

[dependencies.serde]
version = "1.0"
features = ["derive"]