# yaml-language-server: $schema=https://squidfunk.github.io/mkdocs-material/schema.json

site_name: wiki-tui
site_url: https://wiki-tui.net
site_author: Builditluc

repo_name: builditluc/wiki-tui
repo_url: https://github.com/builditluc/wiki-tui

theme:
  name: material
  language: en
  custom_dir: docs/.overrides
  icon:
    logo: material/console
    repo: fontawesome/brands/github
  favicon: assets/images/logo.png
  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.sections
    - navigation.indexes
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.copy
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default 


      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to system preference

nav:
  - Home: index.md
  - Getting Started:
    - Installation: getting-started/installation.md
    - Using the CLI: getting-started/using-cli.md
    - License: getting-started/license.md

    - Contributing: 
      - contributing/index.md
      - Creating a Bug and Crash report: contributing/bug-report.md
      - Requesting / Implementing a feature: contributing/feature-request.md
      - Modifying the project: contributing/developing.md
      - Maintainers Guides: contributing/maintainers.md

  - Configuration:
    - configuration/index.md
    - Changing the Theme: configuration/theme.md
    - Configuring the Pages: configuration/page.md
    - Api Settings: configuration/api.md
    - Configure the Logging: configuration/logging.md
    - Keybindings: configuration/keybindings.md

  - Changelog:
    - changelog/index.md
    - How to upgrade: changelog/upgrade.md


edit_uri: edit/main/docs/docs/

markdown_extensions:
  - meta
  - attr_list
  - admonition
  - tables
  - md_in_html
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg

plugins:
  - tags
  - social
  - search
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago
  - git-authors

extra:
  version:
    provider: mike
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/builditluc/

copyright: Copyright &copy; 2021 - 2024 Builditluc
